s="anil\nsoftware"
print(s)
a="anil\vsoftware"
print(a)
b="anil\tsoftware"
print(b)
c="anil\bsoftware"
print(c)
d="anil\fsoftware"
print(d)
e="anil\rsoftware"
print(e)
f="anil\"software"
print(f)
g="anil\'software"
print(g)
h="anil\\software"
print(h)
